# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Calthalas
tagline:          Calthalas
url:              http://calthalas.github.io/
paginate:         1
baseurl:          /
author:
  name:           Calthalas
  url:
  email:          calthalas@yahoo.com

# Custom vars
version:          1.0.0
github:
  repo:

#Pages
pages_list:
  About: '/about'
  Archive: '/archive'
